### ISSUE TITLE
discrepency in casing for setup file

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/sandpaper#162]
```r
> list.files(pattern = "setup.+", path = ".", recursive = TRUE, ignore.case = TRUE)
[1] "learners/Setup.md"    "site/built/Setup.md"  "site/docs/Setup.html"
```

the schedule expects `setup.html` (the learner menu has `Setup.html`.

I think we want to keep everything lower case?

**Comment by zkamvar** [comment]
You are correct, we do. I don't know why I had it that way. If you want, you can create a pull request on Monday when I'm not here.

The relevant places that need to be modified are:

Code:
https://github.com/carpentries/sandpaper/blob/c8b534389dbce486bbd29fd28617ad33acbad117/R/create_lesson.R#L39

Tests:
https://github.com/carpentries/sandpaper/blob/b42cb1836dc4bd022c8ecaf94474a24b8073b6f8/tests/testthat/test-build_markdown.R#L96
https://github.com/carpentries/sandpaper/blob/b42cb1836dc4bd022c8ecaf94474a24b8073b6f8/tests/testthat/test-build_markdown.R#L114
https://github.com/carpentries/sandpaper/blob/b42cb1836dc4bd022c8ecaf94474a24b8073b6f8/tests/testthat/test-get_dropdown.R#L53
https://github.com/carpentries/sandpaper/blob/aeb4af053c7ac479eda6b045ce28a125d3291aed/tests/testthat/test-set_dropdown.R#L101
