### ISSUE TITLE
Reuse GitHub Workflows

### ISSUE THREAD

**Issue by zkamvar** [carpentries/sandpaper#199]
We currently strip all code for generating content out of the repository with one exception: github workflows. This was because we could not have centralised workflows that people could run from their lessons.

Luckily, now we can with: https://docs.github.com/en/actions/learn-github-actions/reusing-workflows

I will look into setting these up so that we can absolutely minimize the amount of code needed for these repositories to deploy.

**Comment by ErinBecker** [comment]
All of the GitHub workflows used for lessons are now centralized in https://github.com/carpentries/actions. Closing.
