### ISSUE TITLE
[metadata] Change @type to "TrainingMaterial"

### ISSUE THREAD

**Issue by zkamvar** [carpentries/sandpaper#236]
I reached out to TeSS for information on whether or not the metadata we include is applicable for their catalog and their response was:

> I have had a quick look and I think the only change I would make would be to change the @type to “TrainingMaterial”.
> 
> With that change and a sitemap, I will be able to easily add your content to TeSS automatically.

**Comment by PhilReedData** [comment]
I work in the TeSS team, the information above is incorrect. The `@type` should be `LearningResource`.  https://schema.org/LearningResource

The `TrainingMaterial` is the Bioschemas profile which it conforms to, providing additional information about required, recommended and optional properties. https://bioschemas.org/profiles/TrainingMaterial/1.0-RELEASE

Example:
```javascript
  <script type="application/ld+json">
    {
       "@context": "https://schema.org",
       "@type": "LearningResource",
       "@id": "https://swcarpentry.github.io/shell-novice/index.html",
       "inLanguage": "en",
       "dct:conformsTo": "https://bioschemas.org/profiles/TrainingMaterial/1.0-RELEASE",
       "description": "A Carpentries Lesson teaching foundational data and coding skills to researchers worldwide",
       "keywords": "software, data, lesson, The Carpentries",
       "name": "The Unix Shell",
       "creativeWorkStatus": "active",
       "url": "https://swcarpentry.github.io/shell-novice/index.html",
       "identifier": "https://swcarpentry.github.io/shell-novice/index.html",
       "dateCreated": "2014-10-22",
       "dateModified": "2025-04-15",
       "datePublished": "2025-04-15"
   }
</script>
```
https://validator.schema.org/
