### ISSUE TITLE
sandpaper::serve() + sandpaper::build_lesson() created infinite loop

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/sandpaper#246]
I distractedly set the lesson building with `build_lesson()`, forgetting that I already ran `serve()`, and that seemed to throw R into an infinite loop of building and rebuilding the lesson.

**Comment by zkamvar** [comment]
Thank you for the report! I think the solution here would be to add the `filter = "^site$"` to 
the `servr::httw()` function so that it only responds to changes in the source files.

https://github.com/carpentries/sandpaper/blob/229e78ba2e0fa55fcac830c84abc2372caf5c537/R/serve.R#L32

**Comment by zkamvar** [comment]
Update: it turns out that the `filter` argument needed to be a function that filters the paths. I've included it in #247 

Toby, can you try it out with?

```r
remotes::install_github("carpentries/sandpaper#247")
```

**Comment by tobyhodges** [comment]
Installation seemed to work, but when I run `sandpaper::serve()` I get

```
[Toby is not including the standard logging messages]
Output created: /path/to/lesson-development-training/site/docs/index.html
Error in file.paths(base, ".git") : could not find function "file.paths"
```

**Comment by zkamvar** [comment]
Interactive functions are hard to test. I won’t get to this for another
couple of hours, but if you have edit access, deleting the “s” from that
function name will work.

**Comment by zkamvar** [comment]
I've pushed the update. It should work now.
