### ISSUE TITLE
Local Building lesson fail

### ISSUE THREAD

**Issue by sstevens2** [carpentries/sandpaper#249]
Working on the [lesson development training repo](https://github.com/carpentries/lesson-development-training), and cloned it to my local computer to try out working with sandpaper.

Tried `build_lesson()` and it crashed Rstudio and required a restart so I couldn't see the error.  This error has not been reproducible since.

After the restart I tried using the Build Website shortcut and got the following error.
```
Writing 'instructor/03-audience.html'
Writing '03-audience.html'
Error in dir_map(old, fun, all, recurse, type, fail) : 
  SET_VECTOR_ELT() can only be applied to a 'list', not a 'NULL'
Calls: <Anonymous> ... <Anonymous> -> build_site -> <Anonymous> -> dir_map
Execution halted

Exited with status 1.
```

Interestingly when I called `build_lesson()` again from console, I instead got this error
```
-- Initialising site -------------------------------------------------------------------
── Scanning episodes to rebuild ────────────────────────────────────────────────────────
Writing 'instructor/13-narrative.html'
Writing '13-narrative.html'
── Creating learner profiles ───────────────────────────────────────────────────────────
Writing 'instructor/profiles.html'
Writing 'profiles.html'
── Creating keypoints summary ──────────────────────────────────────────────────────────
Error: 'md_ns' is not an exported object from 'namespace:tinkr'
```

Let me know if that is a helpful amount of info @zkamvar.  Happy to try some solutions as well.

Also wanted to ask, would you prefer we ask questions like this directly on the lesson repo or here in the sandpaper repo?

**Comment by sstevens2** [comment]
Interesting! I (thought I) did update them just prior to running this.  I ran the commands below from the sandpaper docs right before.  I'll double check my session info and try to update again.

```
options(repos = c(
  carpentries = "https://carpentries.r-universe.dev/", 
  CRAN = "https://cran.rstudio.com/"
))
install.packages("sandpaper", dep = TRUE)
```

**Comment by zkamvar** [comment]
One thing to note about {tinkr}: The maintainer of this package did not elect to shift in-development version numbers (i.e. the version has been 0.0.0.9000 for a few years), so when you R is checking the dependencies, it does not know that it needs to update {tinkr} when you install {sandpaper}. This will change as I am taking over maintenance of {tinkr} and will eventually get it on CRAN.

**Comment by zkamvar** [comment]
And thank you for your patience with this!
