### ISSUE TITLE
Create instructor aside class for displaying instructor notes

### ISSUE THREAD

**Issue by zkamvar** [carpentries/sandpaper#26]
The `<aside>` tag is a neat feature of HTML5 that allows you to write side-bars in HTML without the use of JavaScript. 

We can have contributors create instructor notes that can be hidden by using fenced div tags:

```markdown

This is some markdown text

::::::::::::::::::::: instructor

This will be hidden, but appear on the side if a button is pressed.

:::::::::::::::::::::::::::::::

```

It's possible to achieve this via lua filters, which are available since pandoc 2.0. The R Markdown Cookbook describes these in detail: https://bookdown.org/yihui/rmarkdown-cookbook/lua-filters.html. One particular inspiration is the {govdown} package, which has [this bit of lua that describes how we can replace a div tag with pretty much anything we want](https://github.com/ukgovdatascience/govdown/blob/77f8cf2d88bace37382bc39ed26e30db944d7558/inst/rmarkdown/resources/govuk.lua#L30-L59)

If I manipulate this for our purposes, it would look like this:

```lua
-- Deal with fenced divs
Div = function(el)

  -- look for the instructor tag
  v,i = el.classes:find("instructor")
  -- If the index is not missing
  if i ~= nil then
    -- remove this class from the div tag
    el.classes[i] = nil

    -- create a new pandoc element, add raw HTML, 
    -- and fill it with the content of the div block
    local html
    local res = pandoc.List:new{}

    html = '<aside class="instructor">'

    table.insert(res, pandoc.RawBlock('html', html))

    for _, block in ipairs(el.content) do
      table.insert(res, block)
    end
    table.insert(res, pandoc.RawBlock('html', '</aside>'))

    return res
  end
  return el
end
```

**Comment by zkamvar** [comment]
Here's what the filter looks like (with css applied): 
![image](https://user-images.githubusercontent.com/3639446/98851805-a23bcb80-240b-11eb-9130-535b1a2dd3f0.png)

**Comment by zkamvar** [comment]
Note: with this setup, we can also define a JS rule for instructor class elements to hide or appear on button click. The benefit of having them in an `<aside>` tag is that they should not interrupt the flow of the document even if they are present.

**Comment by fmichonneau** [comment]
This makes me very happy!

**Comment by zkamvar** [comment]
done and superseded by new lesson
