### ISSUE TITLE
Enumerate Episodes

### ISSUE THREAD

**Issue by fiveop** [carpentries/sandpaper#276]
In the old template, episodes were enumerated, so you could refer to, for example, the first episode. This is no longer possible.

**Comment by zkamvar** [comment]
Can you clarify what you mean by enumerate? You can specify the episode order in the `config.yaml`: https://carpentries.github.io/sandpaper-docs/editing.html#organization

**Comment by fiveop** [comment]
In the overview of the old template, episode titles are prefixed by increasing numbers, e.g. https://swcarpentry.github.io/shell-novice/.

In the new template’s ToC that is not the case.

(Though I noticed that on the old episode pages the titles are not prefixed.)

**Comment by zkamvar** [comment]
Gotcha! 

the prefixes in the schedule are still there, but we have moved it to the instructor view:

https://carpentries.github.io/sandpaper-docs/instructor/#schedule

We replaced the schedule in the learner view with the setup: https://carpentries.github.io/sandpaper-docs/#setup

**Comment by zkamvar** [comment]
That being said, I don't see the harm in prefixing the numbers for the episode list.

**Comment by zkamvar** [comment]
I realise this was fixed in #277
