### ISSUE TITLE
Standardize setup page

### ISSUE THREAD

**Issue by sstevens2** [carpentries/sandpaper#28]
From our discussion in maintainers meeting.

We thought it would be good to have sections for the both data download part of setup and then also the software install part of setup on the setup page.

**Comment by zkamvar** [comment]
To clarify, it would be something like this, making sure that the Data section and Software Setup section are always one after another? 

```markdown
## Data

Download the [data zip file](data/data.zip) and unzip it to your Desktop

## Software Setup

### Windows

Lorem

### MacOS

ipsum

### Linux

dolor
```

**Comment by sstevens2** [comment]
Yep, that looks great!

**Comment by zkamvar** [comment]
Thank you for the feedback! I will make sure this is included in the design and will report back here once a workable version is ready  :)
