### ISSUE TITLE
create_episode should create slugified filename from episode title

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/sandpaper#294]
When I used `sandpaper::create_episode` to add a new episode file to my lesson, the name of the file created included whitespace from the title I specified for the lesson.

I ran 

```R
sandpaper::create_episode('Defining Episode Objectives')
```

and got a new episode file called `26-Defining Episode Objectives.Rmd` i.e. including the spaces from my specified episode title.

It would be great to get a new file called `26-defining-episode-objectives.Rmd` instead.

**Comment by zkamvar** [comment]
This makes a lot of sense! It also gives me the opportunity to replace the title element in the actual episode text.
