### ISSUE TITLE
headings with the title or ID of "resources" are displayed larger

### ISSUE THREAD

**Issue by zkamvar** [carpentries/sandpaper#359]
There is a fun little bug that I saw on someone's personal lesson where they included a section called "resources" at the end of the document. This document happens to have larger than normal text:

<details>
<summary>Markdown and Screenshots of problem</summary>

```markdown
## Resources

 - [Tidy data vignette](https://cloud.r-project.org/web/packages/tidyr/vignettes/tidy-data.html)
 - [Tidy data paper](https://vita.had.co.nz/papers/tidy-data.pdf)
 - [Data import cheat sheet](https://github.com/rstudio/cheatsheets/blob/main/data-import.pdf)


::::::::::::::::::::::::::::::::::::: keypoints 

- Keeping your data tidy makes it easier to work with
- Use `readxl::read_excel()` to import data from excel
- Use `readr::read_delim()` to import data from delimited text files

::::::::::::::::::::::::::::::::::::::::::::::::
```

![screenshot of resources section with large text](https://user-images.githubusercontent.com/3639446/199561968-ef010ca6-f22c-459a-94c8-15cb9c5f3077.png)

compared to a regular heading:

![screenshot of a different section with default text size](https://user-images.githubusercontent.com/3639446/199562189-0483deda-4e10-493a-ac07-80aac9464f32.png)

</details>

## source of problem

It's coming from the fact that we have [anchors for `#chapters` and `#resources` in the CSS for varnish](https://github.com/carpentries/varnish/blob/6154d6f2b02d06aac74abd18047d987878188b68/source/stylesheets/sidenav.scss#L95-L99)

**Comment by zkamvar** [comment]
It turns out that this also poses a navigation problem along with the following headings:

 - chapters (chapter list in the desktop site)
 - resources ("more" menu in the mobile site)
 - to-top (the to top button)
 - expand-code (the "expand all code" button)
 - instructor (mobile view link to instructor view menu)
 - language (mobile view link to language dropdown)
 - eye (anchor for the eye in mobile view; used to add padding to the SVG icon)

I get a feeling that the majority of these are workarounds in the CSS, but it presents a challenge on our side for heading validation that we should not have to do.

**Comment by zkamvar** [comment]
tracking in https://github.com/carpentries/varnish/issues/85

**Comment by ErinBecker** [comment]
Fixed with https://github.com/carpentries/varnish/pull/147
