### ISSUE TITLE
use XXhXX instead of XX:XX for schedule tables

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/sandpaper#361]
As suggested in https://github.com/carpentries/conversations/issues/40, using 03h00 instead of 03:00 helps to clarify that the schedule tables are describing timings in hours and minutes as opposed to minutes and seconds or anything else.

**Comment by zkamvar** [comment]
I think even 03h00 would be slightly confusing. I think something like 03h 00m would be better?
