### ISSUE TITLE
404 error for 'Glossary' link when using workbench template

### ISSUE THREAD

**Issue by elichad** [carpentries/sandpaper#401]
On the template site https://carpentries.github.io/workbench-template-md/ (and thus any sites that use that template), the 'Glossary' link gives a 404. It's targeting https://carpentries.github.io/workbench-template-md/reference.html#glossary but `reference.html` doesn't exist.

**Comment by zkamvar** [comment]
This is because I had neglected to generate the `learners/reference.md` file in the [`create_lesson()` function](https://carpentries.github.io/sandpaper/reference/create_lesson.html).

Thank you for reporting this, Eli.
