### ISSUE TITLE
Issue with pandoc version requirements?

### ISSUE THREAD

**Issue by ManonMarchand** [carpentries/sandpaper#410]
Hello all,

I tried doing `sandpaper::serve()` on a fresh install. I have the following output:

```
sandpaper requires pandoc version 2.11 or higher.
! You have pandoc version 2.5 in /usr/bin
→ Please visit <https://pandoc.org/installing.html> to install the latest version.
Erreur : Incorrect pandoc version
```
which seems strange, version 2.5 is higher than 2.11

Do you know what's happening here?

Thanks!

**Comment by zkamvar** [comment]
Thank you for opening the issue, @ManonMarchand. Even though it was able to be resolved on your end, I really appreciate honest feedback like this. 

I'm wondering, is there a way this error message could be improved? Could there be more spacing around the messages or a comparison added `(2.5 < 2.11)`? 

```
sandpaper requires pandoc version 2.11 or higher.
! You have pandoc version 2.5 in /usr/bin
→ Please visit <https://pandoc.org/installing.html> to install the latest version.
Erreur : Incorrect pandoc version
```

**Comment by ManonMarchand** [comment]
No sorry, I think the message is good and I was just a bit too tired.
