### ISSUE TITLE
[PR workflow] file reversions sill show up as changed.

### ISSUE THREAD

**Issue by zkamvar** [carpentries/sandpaper#411]
In https://github.com/datacarpentry/r-raster-vector-geospatial/pull/387 there were two files modified and the maintainer requested for one file to be reverted to its original state.

These were the changes recorded initially:

```
 03-raster-reproject-in-r.md                        | 365 ++++++++++-----------
 04-raster-calculations-in-r.md                     | 352 +++++++++++---------
 chm_ov_SJER.tiff                                   | Bin 6656549 -> 6656567 bytes
 ...in-r-rendered-challenge-code-reprojection-1.png | Bin 210212 -> 232693 bytes
 ...ter-reproject-in-r-rendered-plot-DTM-hill-1.png | Bin 49505 -> 49855 bytes
 ...oject-in-r-rendered-plot-projected-raster-1.png | Bin 129256 -> 141502 bytes
 ...-calculations-in-r-rendered-chm-harv-hist-1.png | Bin 4668 -> 5196 bytes
 ...lations-in-r-rendered-chm-harv-hist-green-1.png | Bin 4286 -> 4743 bytes
 ...alculations-in-r-rendered-chm-harv-raster-1.png | Bin 28264 -> 28265 bytes
 ...tions-in-r-rendered-compare-chm-harv-sjer-1.png | Bin 4668 -> 5196 bytes
 ...tions-in-r-rendered-compare-chm-harv-sjer-2.png | Bin 4220 -> 4721 bytes
 ...er-calculations-in-r-rendered-create-hist-1.png | Bin 4668 -> 5196 bytes
 ...tions-in-r-rendered-sjer-chm-overlay-hist-1.png | Bin 4220 -> 4721 bytes
 md5sum.txt                                         |   4 +-
 14 files changed, 375 insertions(+), 346 deletions(-)
```

After the reversion, where `episodes/03-raster-calculations-in-r.md` was reverted (in https://github.com/datacarpentry/r-raster-vector-geospatial/pull/387/commits/f7f6c2c682c35b53909759e619f1770cb440a1af) these are the changes recorded:

```
 03-raster-reproject-in-r.md                        | 365 +++++++++++----------
 04-raster-calculations-in-r.md                     | 352 +++++++++++---------
 chm_ov_SJER.tiff                                   | Bin 6656479 -> 6656567 bytes
 ...in-r-rendered-challenge-code-reprojection-1.png | Bin 232693 -> 210212 bytes
 ...ter-reproject-in-r-rendered-plot-DTM-hill-1.png | Bin 49855 -> 49505 bytes
 ...oject-in-r-rendered-plot-projected-raster-1.png | Bin 141502 -> 129256 bytes
 ...-calculations-in-r-rendered-chm-harv-hist-1.png | Bin 4668 -> 5196 bytes
 ...lations-in-r-rendered-chm-harv-hist-green-1.png | Bin 4286 -> 4743 bytes
 ...alculations-in-r-rendered-chm-harv-raster-1.png | Bin 28264 -> 28265 bytes
 ...tions-in-r-rendered-compare-chm-harv-sjer-1.png | Bin 4668 -> 5196 bytes
 ...tions-in-r-rendered-compare-chm-harv-sjer-2.png | Bin 4220 -> 4721 bytes
 ...er-calculations-in-r-rendered-create-hist-1.png | Bin 4668 -> 5196 bytes
 ...tions-in-r-rendered-sjer-chm-overlay-hist-1.png | Bin 4220 -> 4721 bytes
 md5sum.txt                                         |   4 +-
 14 files changed, 390 insertions(+), 331 deletions(-)
```

However, the diff of this file shows that the changes were relative to the _revision_ and not relative to the main branch: https://github.com/datacarpentry/r-raster-vector-geospatial/commit/cd8ff0bb3637ca0711d32a4565542fa819c14f30#diff-915978fbeda876c984ac91d998c58c5d534d940bd345ac94de3f492756c26c54

I'm not exactly sure _why_ this is happening because the workflow uses the `md-outputs` branch as a base every time, but clearly this diff shows different.

**Comment by zkamvar** [comment]
This is actually a cache invalidation issue with multiple PRs:

Episode 3 was updated in https://github.com/datacarpentry/r-raster-vector-geospatial/commit/7f83d2db9ed2311b9f350e5d3025c9f40cd654c8,

BUT, because https://github.com/datacarpentry/r-raster-vector-geospatial/pull/387 ALSO had episode 3 modified in the PR, the change reflected the fact that the update happened. I'm not exactly sure but I believe this is a rare occurance where a file is reverted to an old form after the file was updated to the newer form in the main branch.

It gets kinda confusing here, but I think ultimately everything will be okay.

**Comment by drakeasberry** [comment]
@zkamvar It looks as though this has overwritten the changes committed in Episode 3, commit 7f83d2d. Anyway to bring these changes that @albhasan made?

**Comment by zkamvar** [comment]
Oh wait... so everything was _not_ okay?

**Comment by albhasan** [comment]
Hello @zkamvar,

I followed your instructions but I had to made a small change to the code (removed a new line character)  to be able to commit and make a new PR. Otherwise git says there is nothing to commit. I hope this fix the issue.

Cheers!

**Comment by zkamvar** [comment]
Oh this is weird. I would close that PR and try again by pulling the file from https://github.com/datacarpentry/r-raster-vector-geospatial/commit/c67c61a44eda34bd7c42a4eca764ba54d412e808:

```
# make sure you are up-to-date on the main branch
git switch main
git pull
# check out episode 3 to the main branch, and create a new branch and commit
git checkout c67c61a44eda34bd7c42a4eca764ba54d412e808 episodes/03-raster-reproject-in-r.md
git switch -c new-m2022q1_e3
git restore --staged episodes/03-raster-reproject-in-r.md
git add episodes/03-raster-reproject-in-r.md
git commit -m 'fix episode 3 reversion'
```

hopefully third time is to charm

**Comment by zkamvar** [comment]
To clarify: this would have happened regardless of infrastructure. The commit to update episode 3 (https://github.com/datacarpentry/r-raster-vector-geospatial/pull/386/commits/c67c61a44eda34bd7c42a4eca764ba54d412e808) was the _same commit_ in both https://github.com/datacarpentry/r-raster-vector-geospatial/pull/386 and https://github.com/datacarpentry/r-raster-vector-geospatial/pull/387. 

The commit to revert episode 3 (https://github.com/datacarpentry/r-raster-vector-geospatial/commit/f7f6c2c682c35b53909759e619f1770cb440a1af) was made in https://github.com/datacarpentry/r-raster-vector-geospatial/pull/387. 

I think the thing to understand about [`git revert`](https://git-scm.com/docs/git-revert) commits is that Git does not assing any special meaning to them. To Git, that was just another point in time where the authors said "I would like to change this file again."
