### ISSUE TITLE
[config] add optional `analytics` key

### ISSUE THREAD

**Issue by zkamvar** [carpentries/sandpaper#438]
Stemming from https://github.com/carpentries/varnish/issues/37, it should be possible for users to optionally add in an analytics key to their websites in the YAML config (yes, YAML is hell).

@fiveop has suggested the following in https://github.com/carpentries/varnish/issues/37#issuecomment-1126201961:

> ... you could have three options: none, carpentries, <custom>

In that vein, we could have the following scenarios.

Default, no config: 

```yaml
# no option present meaning no analytics will be added
```

Carpentries Lesson:

This is only applied to our official lessons. 

```yaml
analytics: 'carpentries'
```

Custom config:

```yaml
analytics: |
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id={YOUR TRACKING ID}"#' ></script>
  <script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{YOUR TRACKING ID}');
  </script>
```

**Comment by froggleston** [comment]
Closing this due to #586 and we can open new issues for improvements in future.
