### ISSUE TITLE
GitHub Actions: Translate warnings and errors to workflow commands

### ISSUE THREAD

**Issue by zkamvar** [carpentries/sandpaper#50]
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message

I've found it helpful in pull requests when warnings and errors label the lines where an error is found. This is achieved in GitHub Actions via workflow commands that are strings output to stdout that start with `::`.

For example, [this warning](https://github.com/zkamvar/testme/commit/1ab80e278a57a2f038f35b74e8f2777cc3efbc62#annotation_744820416) was generated from [this workflow command](https://github.com/zkamvar/testme/commit/c4589e565dd87f0181126a3a4e17811f239a5b63#):

```
::warning file=episodes/01-introduction.Rmd,line=10,col=5::This is a warning
```

**Comment by ErinBecker** [comment]
This has been implemented, as demonstrated by the output below showing an error message for image missing alt text. 

```
── Validating Fenced Divs ──────────────────────────────────────────────────────
── Validating Internal Links and Images ────────────────────────────────────────
! There were errors in 1/123 images
◌ Images need alt-text <https://webaim.org/techniques/hypertext/link_text#alt_link>
```
