### ISSUE TITLE
The width of the 'Questions' column at the beginning of the lesson doesn't scale properly

### ISSUE THREAD

**Issue by ShrRa** [carpentries/sandpaper#524]
The 'Questions' field at the beginning of the lesson does not scale well, and as a result, the text is wrapped so much that the content becomes unreadable. It seems to be the problem with styles 'col-md-4', because the 'Objectives' field, which uses 'col-md-8' CSS class, scales normally.
![Screenshot from 2023-09-25 18-46-43](https://github.com/carpentries/sandpaper/assets/16464387/383fc917-290e-4af7-a5d5-0539768945fe)

**Comment by zkamvar** [comment]
Thank you for opening this. It is related to the following issues: 

https://github.com/carpentries/sandpaper/issues/299, https://github.com/carpentries/varnish/issues/83, and https://github.com/carpentries/workbench/issues/57

I'm going to mark this as "duplicated", but plese know that we have it in the queue for @carpentries/workbench-maintainers to work on.

**Comment by froggleston** [comment]
I believe this to be fixed through https://github.com/carpentries/varnish/issues/83 so will close this for now. However, #299 might still need addressing if further card styling is required.
