### ISSUE TITLE
Add build_path option for sandpaper::serve

### ISSUE THREAD

**Issue by fherreazcue** [carpentries/sandpaper#536]
We produced a [docker container](https://github.com/UoMResearchIT/sandpaper-docker) with a  working copy of the carpentries workbench, which allows you to serve the site and update it live while rendering it in localhost, without having to install Rstudio and all the stuff around it.
On linux, this works ok, but on macOS there are problems with permissions. The bind mount necessary to continuously render the site makes it so that created directories within the bind mount do not have write permissions, and so the sandpaper::build_lesson command fails.
Even manually and painstakingly granting permissions to each created folder ends up failing, because it checks that the site/docs directory was not already there, and so it fails to copy files over.
We have tried to resolve this on the docker side, but failed to do so. We are unsure if sandpaper is changing the permissions internally, and it is conflicting with the macOS bind mount.
If the lesson files are moved outside of the bind mount, the serve works ok, but this defeats the purpose of live rendering. 

The only solution we can think of is to specify a different build site path, so that the source files can be edited live, but the site/* items need to be outside of the mount.

We noticed that the [build_site](https://carpentries.github.io/sandpaper/reference/build_lesson.html) function has an `override` input to potentially change the build path, but could not find any usage examples, and it does not seem to propagate up to the sandpaper::serve function, so some tweaking seems to be necessary.

Thanks

Note: use [this branch](https://github.com/UoMResearchIT/sandpaper-docker/tree/arm) to test on arm architectures.

____
To reproduce on an arm macOS run:
```
git clone https://github.com/UoMResearchIT/sandpaper-docker.git
git checkout arm
docker build -t sandpaper:arm
docker run -p 4321:4321 -v $PWD/your-site/:/siteroot/ sandpaper:arm
```

**Comment by zkamvar** [comment]
Hi @fherreazcue, just checking to see if this solution works for you?

**Comment by fherreazcue** [comment]
Hello @zkamvar , and sorry for the late reply, had not had a chance to look at this.

I had problems using `pak`, because the container is rather a minimal R version, but managed to install it with:
```
installr carpentries/sandpaper#537
```

I could then not make the R instructions work, but the instructions you added in #537 for bash worked great!
```
TMP=$(mktemp -d)
SANDPAPER_SITE=${TMP} R -q -e 'sandpaper::serve(quiet = FALSE)'
```

Thanks a lot, will this be included in a release soon?

**Comment by zkamvar** [comment]
Yes, we will include this in the release of version 0.15.0, which I have tentatively scheduled for November 29th.

**Comment by fherreazcue** [comment]
Thanks again for this, the [docker image for mac](https://github.com/UoMResearchIT/sandpaper-docker/pkgs/container/sandpaper/153213057?tag=latest_arm) is now working.

**Comment by zkamvar** [comment]
Thank you! Would you mind adding your solution to https://github.com/carpentries/workbench/issues/39?
