### ISSUE TITLE
Do not rewrite special links such as mailto: (and similar non-path links)

### ISSUE THREAD

**Issue by apirogov** [carpentries/sandpaper#538]
When using a clickable E-Mail link, such as `mailto:HMC@fz-juelich.de`, it is being prefixed by the base URL and thereby breaking it, resulting in

* `file:///local/home/a.pirogov/projects/ias9/scientific-metadata/site/docs/mailto:HMC@fz-juelich.de` (locally)
* `https://carpentries-incubator.github.io/scientific-metadata/mailto:HMC@fz-juelich.de` ([online](https://carpentries-incubator.github.io/scientific-metadata/instructor/general-lesson-information.html#get-in-touch))

Apparently it is interpreted as a "local path".

**Comment by zkamvar** [comment]
yikes! Mea culpa. I'll add a catch for that.

**Comment by zkamvar** [comment]
I've opened a patch in #539 and have tested it locally. I will do a patch release once I confirm that [the remote integration test works](https://github.com/carpentries/workbench-integration-test/actions/runs/6815823668/job/18535781392)

**Comment by zkamvar** [comment]
The remote test [appears to be working as shown in this HTML preview](https://htmlpreview.github.io/?https://github.com/carpentries/workbench-integration-test/blob/9b8be6805ebf5c30a7d25a113f03646e28fb955d/instructor/general-lesson-information.html)

**Comment by zkamvar** [comment]
I have released this to the R-universe and should be available globally within the hour

**Comment by apirogov** [comment]
Thanks for the quick fix :slightly_smiling_face:
