### ISSUE TITLE
index page is README instead of index

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/sandpaper#56]
![Screenshot from 2021-01-27 09-00-21](https://user-images.githubusercontent.com/5502922/105960897-d9556c80-604b-11eb-9e2e-ed106fc6fb65.png)

**Comment by zkamvar** [comment]
Note: this is from https://github.com/zkamvar/new-programming-with-r/commit/ddf9a5c6323679eb121be27f9c6fe14c74f45797
