### ISSUE TITLE
Strange wrapping of titles in Chrome when using a Large font size

### ISSUE THREAD

**Issue by dpshelio** [carpentries/sandpaper#570]
Steps to replicate it:

1. In Chrome/chromium, got to settings, appearance and set Font size to Large.

![Chrome_settings](https://github.com/carpentries/sandpaper/assets/963242/07e5a1d1-5046-438f-9182-307fb4872f4c)

2. Visit an episode, and you'll see this.

![chrome-wrapping](https://github.com/carpentries/sandpaper/assets/963242/27577c8a-bce3-4fd6-84f2-3f08860f6ce5)

I've also got the same behaviour in Firefox, though the font size is not selected as "shirt sizes" as in Chrome, but in pixels. The same effect happens when a font size larger than 16 is used (at least for Noto Serif).

![Firefox-settings](https://github.com/carpentries/sandpaper/assets/963242/a1dddb49-71d9-4893-9368-04d7359b6832)

I've never changed the font of either of the browsers, so I imagine this uses the default font available. 

Also note, that zooming into the page (<kbd>Ctrl</kbd>+<kbd>+</kbd>) with the normal font size, doesn't produce this problem while increasing the size.

In my case, the screenshots are from Linux, but I've seen the same on chrome under macOS (@davecash75).

It may be related with #359

**Comment by ErinBecker** [comment]
Fixed with https://github.com/carpentries/varnish/pull/147
