### ISSUE TITLE
Builds fail when ÷ character is formatted as code without syntax highlighting

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/sandpaper#589]
(Derived from a report by @knarrff on Slack)

Something catastrophic happens to the lesson build when a `÷` character is included in a page, formatted as code but with no language specified for syntax highlighting.

I created a minimal example at https://github.com/tobyhodges/refactored-sniffle, demonstrating how 

````
```julia
a ÷ b
```
````

works fine, but

````
```
a ÷ b
```
````

causes something bad to happen to the build. 
(Not shown, but reproduced on my local system, is that inline code (i.e. enclosed in single backticks) fails without a language class applied, but works fine with e.g. `{.julia}` added afterwards.)

The GitHub Actions logs on that example repo suggest that the failure happens even before the lesson site starts to be built. I cannot confirm that, but have been able to reproduce the error with a local build of the linked minimal example.

**Comment by tobyhodges** [comment]
Following up, this seems to be a problem with `pkgdown`: [a second minimal example using pkgdown directly](https://github.com/tobyhodges/studious-doodle) gives the same problem when running `pkgdown::build_site()`.

**Comment by zkamvar** [comment]
Linking https://github.com/r-lib/downlit/issues/189 so that it's clear where this is being fixed.

**Comment by tobyhodges** [comment]
The new version of downlit has been released and have confirmed that lesson builds are now succeeding.
