### ISSUE TITLE
Document how to link external images

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/sandpaper#60]
it seems that relying on `knitr::include_graphics()` has some advantages but what do we do for non-R based lessons. Do we ask them to use Rmd just for this feature until we can evaluate other languages?

related to #58

**Comment by zkamvar** [comment]
I was thinking that we would just ask people to refer to images the same way anyone would using markdown syntax:

https://zkamvar.github.io/stunning-barnacle/#links

 - Link to other episodes: use `[link text](episode-name.html)`
 - Link to figure for episode: use `![Alt text](fig/figure-name.png)`
 - Link to references in learners folder: `[link text](../learners/references.html)`

**Comment by zkamvar** [comment]
The advantage of `knitr::include_graphics()` is that it can auto-calculate the image size and format the output for different document types. The disadvantage is that it's not markdown syntax and would increase the cognitive load for people who are not familiar with RMarkdown.

**Comment by zkamvar** [comment]
- [x] relative path images
 - [ ] external images
 - [ ] encourage RMarkdown users to use `knitr::include_graphics()`
 - [ ] validation: figure size practices
 - [ ] validation: figure color practices

**Comment by zkamvar** [comment]
See: https://github.com/carpentries/styles/issues/161
