### ISSUE TITLE
cat("::group::Register Repositories\n") fails

### ISSUE THREAD

**Issue by chrbknudsen** [carpentries/sandpaper#605]
The build full site workflow fails right after 
 cat("::group::Install remotes\n")
With the message:
Error: Rscript: command not found

Setting install-r: to true in sandpaper-main.yaml resolves the issue.

**Comment by froggleston** [comment]
@chrbknudsen can you point us to your repository and workflow where this fails?

**Comment by froggleston** [comment]
I found an example in one of your repositories. This is most likely because you are using ubuntu 24.04. Could you roll back to 22.04 (jammy) and try again? 24.04 is known to be very buggy at the moment so we would recommend sticking to 22.04 for a few more months at least to allow issues to be resolved in the main OS.

**Comment by chrbknudsen** [comment]
Thank you! That appears to solve the problem. 
Let me add that the workflow came directly from the sandpaper workflows - it would appear that the problem might not be specific to my repo.

**Comment by froggleston** [comment]
That's correct @chrbknudsen - this would affect all future lesson builds so we've raised a PR to revert to 22.04 in the sandpaper workflows. Thank you for raising this issue!

**Comment by btmoyers** [comment]
I am having the same issue with building a modified lesson (https://github.com/btmoyers/bash-genomics) which worked in August 2024. Any suggestions for modifications I can make on my own end?

**Comment by btmoyers** [comment]
Nevermind! I followed through to your workaround and just copied it over. Thanks!
