### ISSUE TITLE
German language support not working ..

### ISSUE THREAD

**Issue by martin-raden** [carpentries/sandpaper#609]
Hi @froggleston 

thanks for the fast integration of the German translation into release 0.16.8.

Unfortunately, it is not working in my Carpentry Tutorial ... 😢 

```yaml
lang: de
```
https://github.com/Dr-Eberle-Zentrum/FDM-basics/blob/d81fd8c90ae4a00a2ff3309a54016df589083593/config.yaml#L22

uses the English fallback... see build output at... (which references the recent sandpaper version in the footer)

  https://dr-eberle-zentrum.github.io/FDM-basics/

Switching to `lang: uk` works...

Any ideas here?

Thanks,
Martin

**Comment by martin-raden** [comment]
it seems the `inst/po` folder doesnt feature the `de` data ... ie. no `.mo` file was created ..

**Comment by martin-raden** [comment]
Maybe missed this?

https://github.com/carpentries/sandpaper/blob/d5666211767f81e4e959b1dda4ba0e934bc21ae4/vignettes/translations.Rmd#L180

**Comment by froggleston** [comment]
Hi @martin-raden - yes this is correct and an oversight on my part so sorry for missing this!

I have built the translation files and committed them, so you should be able to build your lessons locally with the main branch. In an upcoming release it will be included properly.

**Comment by martin-raden** [comment]
👍

**Comment by froggleston** [comment]
This should now be fixed in 0.16.9, released just now!

**Comment by martin-raden** [comment]
Many thanks! I just tested and it worked like a charm! 👍
