### ISSUE TITLE
sandpaper-main.yml is marked as invalid

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries/sandpaper#611]
When adapting `sandpaper-main.yml` in a lesson based on the workbench template the file is marked as invalid by the 'Check PR' step in the Record PR number step. Thereby skipping the 'build' action that comes after it.

This has nothing to do with the change itself, but with the original version of the file that is now suddenly detected as being changed and therefore being checked for validity. See this example: https://github.com/olgaminaeva/gen-ai-coding/actions/runs/11329790276/job/31506510651?pr=12

The .yml is valid, in the GitHub editor I do see this warning:

<img width="686" alt="image" src="https://github.com/user-attachments/assets/dff0156a-3d27-4250-a4ba-b3556bec8d71">

**Comment by froggleston** [comment]
The underlying issue of R not being installed is resolved in version 0.16.9 workflows, and I see your repo is using 0.16.7, so please update your sandpaper workflows using the relevant action, and this should work.

**Comment by froggleston** [comment]
Looks to be fixed, referencing https://github.com/olgaminaeva/gen-ai-coding/pull/12
