### ISSUE TITLE
Provide an option in config.yaml for automated/non-automated episode numbering 

### ISSUE THREAD

**Issue by anenadic** [carpentries/sandpaper#623]
Automated episode numbering is not always suitable - it would be good to have a parameter to control this. E.g. see our lesson's episodes screenshot:

<img width="916" alt="image" src="https://github.com/user-attachments/assets/823e0ab5-5157-4bf7-83ed-b78e6b776b21">

Because we have a set of episodes grouped in a 'non-standard' way (i.e. sections)- we'd ened our own numbersing scheme.

**Comment by froggleston** [comment]
Hey @anenadic - I'm not sure how we'd implement this as we would not know how to handle non-standard episode structures by default in the Workbench. Do you have a link to the lesson so I could see how you have the structure laid out?

**Comment by anenadic** [comment]
Hi @froggleston, we have a lesson that is split into 5 sections: https://carpentries-incubator.github.io/python-intermediate-development/.

When we translated it to the new Workbench format we got the episode list numbered as in the screenshot above. Without automated numbering, we could try to have:

-  Section 1 title
- 1.1 episode title
- 1.2 episdoe title 
- ...
- Section 2 title
- 2.1 episode title
- ...

To indicate that episodes fall within sections. 

I can see how this can be difficult and I am not familiar enough with the Workbench to offer a fix myself. Perhaps a parametrer "episode_numbering: false"  in `config.yml` and then use episode titles only in the sidebar (and we control the numbering in the titles)?

**Comment by froggleston** [comment]
Thank you for the info @anenadic! This isn't currently possible, but the quickest way to get something close to what you want is to number your episodes so they would represent your overall section, e.g. 01-foo.md, 02-bar.md, and within each of these your main h2 blocks would represent your internal "episodes", e.g. in 01-foo.md, `## 1.1 First episode`.

Would that work for now?

**Comment by anenadic** [comment]
> Thank you for the info @anenadic! This isn't currently possible (and would not be a high priority for development currently given our capacity), 
Totally get it.

but the quickest way to get something close to what you want is to number your episodes so they would represent your overall section, e.g. 01-foo.md, 02-bar.md, and within each of these your main h2 blocks would represent your internal "episodes", e.g. in 01-foo.md, `## 1.1 First episode`.
> 
> Would that work for now?
So the actual episodes then just become "pages" that we link to, rather then show up in the sidebar navigation? And only "section" pages showing up in sidebar? Could do it like that. Our actual episodes (not section pages) are too long to be included within the section page so we would need separate pages for them. 

It's not a biggie - we will do something to handle this. Thanks for looking into this @froggleston

**Comment by anenadic** [comment]
This is what the sidebar navigation looks like now (the automated numbering mixed in with our internal numbering):

<img width="931" alt="image" src="https://github.com/user-attachments/assets/448c3be1-b6b8-489b-abba-a2d686dca69a">

**Comment by froggleston** [comment]
Ah OK - I think I see what might be feasible, i.e. removing the automatic addition of the list number elements! Let me see what I can come up with. 

Do you have a link to this Workbench version of the lesson so I can test it as closely as possible to your lesson structure?

**Comment by anenadic** [comment]
Here is the fork with the lesson translation: https://github.com/anenadic/python-intermediate-development-earth-sciences

Looking at the source code - this where I identified the sidebar is populated `create_sidebar_item` in https://github.com/carpentries/sandpaper/blob/main/R/utils-sidebar.R#L95 and this is where I sopped - but you know this already.

**Comment by froggleston** [comment]
That's really helpful, thanks @anenadic ! How does this look?

![{CD0DB2F5-7002-4ED2-8186-062291556FD6}](https://github.com/user-attachments/assets/b1b07249-a1b2-4183-987c-a77d78ec3e5f)

**Comment by anenadic** [comment]
That's fantastic @froggleston - massive thanks! 💯
